export const SECONDS_IN_MINUTE = 60;
export const SECONDS_IN_HOUR = SECONDS_IN_MINUTE * 60;

export const DEFAULT_TIMER_TIME = SECONDS_IN_MINUTE * 25;

export const MAXIMUM_TIME_ALLOWED =
  SECONDS_IN_HOUR * 99 + SECONDS_IN_MINUTE * 59;
